#!/bin/bash

if [ -e "_problemS/.ced" ];
then
  git add --all
  git commit -m "végleges változat, csak hiba esetén mod."
  git push origin master
else
  echo "(possibly) unencrypted files...exit\n"
fi
